name: bhavay2
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - images/channels4_profile.jpg
  fonts:
  - family: myfont
    fonts:
    - asset: fonts/AbyssinicaSIL-Regular.ttf

  - family: maven
    fonts:
    - asset: fonts/MavenPro-VariableFont_wght.ttf
